import { Clue, CLUE_COUNT } from "./types";

// === CLUE BOOK ====================================================
// Source: photos of the "CLUES FOR CASES" booklet (clues 1–320).
//
// Best-effort transcription. EVERY clue is `verified: false` until confirmed
// against the printed booklet on the /verify page. Ids missing from CLUE_TEXT
// (currently 300–312, unreadable in the photos) render as "pending". Ids listed
// in UNCERTAIN were hard to read and are flagged for a closer look first.
const CLUE_TEXT: Record<number, string> = {
  1: "Unless the motive was espionage, the Actress is guilty.",
  2: "One of the killers smoked a Cuban cigar.",
  3: "If the Fortuneteller is guilty, she had at least one accomplice.",
  4: "The Diplomat, Fortuneteller, Gambler, and Heiress were having a seance in the library from 6 o'clock until 7, and none of them could have committed the crime during that time.",
  5: "If the Fortuneteller is guilty, the motive was blackmail, espionage, or money; the Fortuneteller is righthanded.",
  6: "At least one of the women is guilty.",
  7: "If there were three or more killers, the motive was either blackmail, money, or revenge. The Doctor and the Cook can narrow down the time of death.",
  8: "There was just one killer.",
  9: "If the Fortuneteller is guilty, the motive was insanity or revenge; the Fortuneteller speaks French.",
  10: "From 7 o'clock on, only the Entrepreneur or Gambler could have committed the crime.",
  11: "If the Entrepreneur is guilty, the motive was not jealousy; the Entrepreneur cannot pick a lock.",
  12: "The victim, Abdul Jamal, collected art objects that have camels as subjects. He carried a cane with a camel's head carved on it, and owned several glass camel sculptures. His body was found in Second Class.",
  13: "The Baroness and Heiress are experts on coins.",
  14: "If the Entrepreneur is guilty, he acted alone.",
  15: "If the Count is guilty, the motive was blackmail or revenge.",
  16: "The only time the Gambler could have committed the crime was between 5 and 6 o'clock, unless he had at least one accomplice who could have done the evil deed at that time.",
  17: "The victim, Horst Hochstapler, was shot to death in First Class. You can eliminate five motives by searching Second Class, sending a telegram asking about the victim, and questioning the Actress or Heiress.",
  18: "If the Count is guilty, the motive was insanity or jealousy.",
  19: "If the Gambler is guilty, the motive was not insanity or revenge.",
  20: "If the Diplomat is guilty, the motive was espionage or jealousy.",
  21: "The murder weapon was a kitchen knife, then either the Entrepreneur, Gambler, or Heiress is guilty.",
  22: "The Gambler is an expert on jewels.",
  23: "At least one woman is guilty, and there were fewer than three killers.",
  24: "The motive could not have been espionage or jealousy.",
  25: "If the Actress is guilty, the motive was blackmail, jealousy, or revenge; the Actress is not an expert in exotic poisons.",
  26: "If the Baroness is guilty, the motive was blackmail or insanity; the Baroness speaks French.",
  27: "The Gambler could only have committed the crime before 6 o'clock.",
  28: "If the Fortuneteller or the Heiress is guilty, the motive was revenge.",
  29: "The murder took place after 6 o'clock.",
  30: "The murder took place between 5 and 7 o'clock.",
  31: "Either the Baroness or Gambler is guilty, but not both of them.",
  32: "If the murder took place between 6 and 7 o'clock, then the Gambler and Heiress must both be innocent.",
  33: "The motive was either blackmail or revenge.",
  34: "If the Fortuneteller is guilty, the motive was blackmail or revenge; the Fortuneteller is not an expert in either coins or jewels.",
  35: "The Actress could only have committed the crime between 6 and 8 o'clock.",
  36: "If you question the Actress and search Second Class, you still will not be able to eliminate espionage or insanity as possible motives.",
  37: "If the Heiress is guilty, the motive was blackmail, insanity, or jealousy; the Heiress is not an expert in exotic poisons.",
  38: "The victim was not killed with a glass camel.",
  39: "If the Baroness is guilty, the motive was espionage or revenge.",
  40: "The Actress and Heiress are guilty, but they had an accomplice.",
  41: "If the Heiress is guilty, the motive was espionage or insanity.",
  42: "All killers had same motive, and it was not insanity.",
  43: "If the Entrepreneur is guilty, the motive was not espionage.",
  44: "If the Heiress is guilty, the motive was blackmail or insanity.",
  45: "If you questioned the Baroness, don't bother talking to the Fortuneteller; but the Count has further information about which suspects are coin experts, and the Actress can tell you more about which are jewel experts.",
  46: "The victim died shortly before 6 o'clock.",
  47: "The murder could not have taken place before 6 o'clock.",
  48: "If the Actress is guilty, the motive was espionage or money.",
  49: "If the Count is guilty, the motive was not espionage or insanity.",
  50: "The killer was recently in Madagascar.",
  51: "If you question the Count, Diplomat, Entrepreneur, and Gambler, you won't be able to get more information about their motives from sending telegrams about them—but the telegrams will tell you which ones speak French.",
  52: "If there were two or more killers, the motive was either blackmail or revenge.",
  53: "The Diplomat and Gambler are not both guilty, although one of them may be.",
  54: "The Entrepreneur is guilty.",
  55: "If the Heiress is guilty, the motive was blackmail or jealousy.",
  56: "The murder weapon was not a knitting needle.",
  57: "The motive had to be insanity, money, or revenge. The victim was an expert in both coins and jewels; he kept a list with him showing whatever he was carrying, and he had a nervous habit of checking and rechecking it to make sure that nothing was missing.",
  58: "Two different kinds of stab wounds on the victim indicate that at least one man and one woman are guilty, and were together while committing the crime.",
  59: "From 5 to 6, the Actress and Diplomat were busy with the Fortuneteller in the drawing room, having their palms read; none of the three of them could have committed the crime during that hour.",
  60: "If the Gambler is guilty, the motive was espionage or insanity.",
  61: "The victim was still alive at 6 o'clock.",
  62: "If the Actress, Baroness, Diplomat, or Fortuneteller is guilty, then the motive was either espionage, money, or revenge.",
  63: "If the Baroness is guilty, the motive was blackmail, insanity, or revenge; the Baroness is righthanded.",
  64: "If the motive was revenge, then at least one of the Actress, Baroness, or Entrepreneur is guilty, and they may have had one or more accomplices.",
  65: "If either the Baroness or the Fortuneteller is guilty, the motive was either blackmail, insanity, or revenge.",
  66: "The motive could not have been espionage or jealousy.",
  67: "If the Entrepreneur is guilty, the motive was not blackmail or money.",
  68: "If the Baroness is guilty, the motive was blackmail, jealousy, or revenge; the Baroness is an expert in both coins and jewels.",
  69: "The motive was not revenge.",
  70: "The motive was insanity.",
  71: "If the motive was revenge, then the murder was premeditated, and the weapon could not have been the cane or glass camel.",
  72: "Both the Baroness and the Gambler speak French.",
  73: "Both questioning the Doctor and searching Second Class, where the murder occurred, will yield essentially the same information; and if you have this information, you don't have to bother searching the Drawing Room or Smoking Lounge Areas. The victim's last name was Doe, but only the Conductor knows whether his first name was spelled \"John\" or \"Jon.\"",
  74: "The murder weapon was not a knife.",
  75: "I heard a shot at 4:30.",
  76: "The victim was shot to death prior to 6 o'clock.",
  77: "I shot the victim at 7:30, but am not sure I killed him.",
  78: "If the Gambler is guilty, the motive was espionage or jealousy.",
  79: "If the Diplomat is guilty, the motive was espionage or revenge.",
  80: "All the killers were present at the scene of the crime when the murder took place; and at least one killer had to know how to pick a lock.",
  81: "If the Baroness is guilty, the motive was not insanity.",
  82: "Neither the Actress nor the Count is guilty.",
  83: "If the Diplomat, Entrepreneur, or Gambler is guilty, the motive was not jealousy.",
  84: "If the Count is guilty, the motive could not have been revenge.",
  85: "There was more than one killer, and the motive was not blackmail.",
  86: "The murder could not have taken place after 7 o'clock.",
  87: "From 5 until 6 o'clock, all the female suspects were in the drawing room; the Fortuneteller was predicting the others' futures.",
  88: "The motive was not insanity.",
  89: "There was only one killer.",
  90: "If the Entrepreneur is guilty, the motive was espionage or insanity; the Entrepreneur is not an expert in either coins or jewels.",
  91: "The murder could not have taken place between 5 and 6 o'clock.",
  92: "If the Heiress is guilty, the motive was not money.",
  93: "The victim was killed in his berth between 6 and 8 o'clock; he was not poisoned, but died from being hit over the head with one of the three objects found near the body: either the glass camel, the cane with a camel's head, or the gun. Searching Second Class will rule out one of these objects.",
  94: "The Actress and Heiress will tell you exactly the same thing, which eliminates two motives.",
  95: "Among the suspects, at least three of the women are not experts in exotic poisons.",
  96: "If the Gambler is guilty, the motive was blackmail, insanity, or money; the Gambler is righthanded.",
  97: "The victim, George Gigolo, was shot to death. If you search First and Second Class and question the Valet, you will have enough information to eliminate two motives.",
  98: "If the murder weapon was a sword, then either the Baroness, Count, Diplomat, or Fortuneteller is guilty.",
  99: "If the Actress is guilty, the motive was not blackmail or revenge.",
  100: "Anyone who was not in the drawing room between 6 and 7 o'clock is innocent.",
  101: "None of the female suspects is ambidextrous; one is lefthanded, three are righthanded.",
  102: "If the Baroness is guilty, the motive was blackmail or jealousy.",
  103: "If the motive was either blackmail or insanity, then at least one of the Baroness, Count, and Gambler is guilty.",
  104: "If the murder took place after 7 o'clock, then the Baroness and Count must both be innocent.",
  105: "If the Heiress is guilty, the motive was money or revenge; the Heiress speaks French.",
  106: "From 6 o'clock until 8, the Baroness and Count were in the dining room.",
  107: "If the Fortuneteller is guilty, the motive was not money; the Fortuneteller cannot pick a lock.",
  108: "Neither the Fortuneteller nor the Gambler could have committed the murder between 5 and 6 o'clock.",
  109: "If the Entrepreneur is guilty, the motive was espionage, insanity, or money; the Entrepreneur is an expert in exotic poisons.",
  110: "If the Entrepreneur is guilty, the motive was not insanity.",
  111: "The Actress could not have committed the crime after 7 o'clock.",
  112: "No one died of being poisoned.",
  113: "If the Diplomat is guilty, the motive was blackmail or jealousy.",
  114: "Either the Actress or Diplomat is guilty.",
  115: "The motive was not jealousy.",
  116: "If the Entrepreneur is guilty, the motive was espionage, money, or revenge.",
  117: "If the Fortuneteller is guilty, the motive was not insanity or money.",
  118: "The Waiter, Porter, and Valet know among themselves which suspects can pick a lock.",
  119: "If the Actress is guilty, the motive was insanity or money.",
  120: "The Count, Entrepreneur, and Gambler were in the dining room from 4 o'clock until 5, and could not have committed the crime during that hour. The Baroness and Heiress were not, however, in the dining room until 6 o'clock, when they arrived for dinner.",
  121: "The murder weapon was a knife, then the Baroness and Count must both be innocent.",
  122: "At some time, a crewman was in the corridor outside the victim's berth. Neither the Actress nor the Baroness has ever owned or worn red shoes.",
  123: "If the Baroness is guilty, the motive was not revenge; the Baroness cannot pick a lock.",
  124: "If the Fortuneteller is guilty, the motive was insanity or jealousy.",
  125: "Both the Actress and the Baroness speak Serbo-Croatian, but only the Actress speaks Italian.",
  126: "A close examination of scuff marks on the floor indicates that at least one man and one woman are guilty, and were together while committing the crime.",
  127: "If either the Count or Gambler is guilty, the motive was money.",
  128: "From 6 o'clock until 7, the Count, Diplomat, and Gambler were in the dining room.",
  129: "The murder weapon was either a knife, an icepick, or a knitting needle.",
  130: "If the Count is guilty, the motive was money; the Count is an expert in coins but not jewels.",
  131: "If the Fortuneteller is guilty, the motive was insanity or jealousy.",
  132: "The victim, Penelope Pennypincher, was strangled with a rope. If you search Second Class, it will be a waste of time to question the Doctor.",
  133: "There was just one conversation between the killer and victim, but I couldn't be sure whether this killer was a man or a woman.",
  134: "What facts can pinpoint the number of killers.",
  135: "The Heiress says about the Count is also true of the Entrepreneur.",
  136: "The only motives I would ever have for murder are espionage or jealousy.",
  137: "If the Heiress is guilty, an occupant of either berth 2 or berth 4.",
  138: "I heard a gunshot at 7:30, and when I went to investigate, I saw the Count running away from the victim's berth.",
  139: "If the Heiress is guilty, the motive was not espionage or jealousy.",
  140: "If the Gambler is guilty, the motive was not espionage; the Gambler knows how to pick a lock.",
  141: "The Count and Valet, between them, know about jewels. The Count's name was Walter de Faulter; his body was found in First Class.",
  142: "If the Count is guilty, the motive was money, espionage, or jealousy; if not, search Second Class.",
  143: "If the murder occurred between 5 and 7 o'clock, then at least one of the Diplomat and Fortuneteller is guilty.",
  144: "If the Gambler is guilty, the motive was not espionage or jealousy.",
  145: "None of the men are experts in coins.",
  146: "The motive could not have been blackmail, insanity, or jealousy.",
  147: "If there were fewer than 3 killers, then the Actress is innocent.",
  148: "The murder must have occurred either between 5 and 6 or between 7 and 8; at least one crewman was in the corridor outside the victim's berth.",
  149: "If the murder weapon was a gun, you can get enough information from the Actress, Gambler, and Entrepreneur together by questioning both the Porter and the Waiter.",
  150: "The victim's first name was spelled 'John'.",
  151: "If the murder took place before 6 o'clock then the Count, Entrepreneur, and Heiress must all be innocent.",
  152: "If the Gambler is guilty, the motive was blackmail or money; the Gambler is an expert in both coins and jewels.",
  153: "If the Actress is guilty, the motive was espionage or revenge.",
  154: "If the Actress committed the crime before 6 o'clock, then she must have lied.",
  155: "If the Diplomat is guilty, the motive was espionage; the Conductor and victim spoke French.",
  156: "One of the four men is guilty; the other three men are innocent.",
  157: "The motive was not espionage or insanity, and unless the killer was a woman, the motive was not revenge.",
  158: "If the Heiress is guilty, the motive was money or revenge.",
  159: "If the Count is guilty, the motive was espionage, insanity, or jealousy; the Count is righthanded.",
  160: "From 4 o'clock until 7, the Fortuneteller and three other suspects held a séance in the library.",
  161: "At least one of the men is guilty.",
  162: "The motive was not blackmail or jealousy.",
  163: "The motive was not espionage, insanity, or jealousy.",
  164: "If the Baroness, Count, Entrepreneur, or Gambler is guilty, then the motive was either blackmail, espionage, or revenge.",
  165: "If the Gambler is guilty, the motive was espionage, insanity, or jealousy; the Gambler is an expert in exotic poisons.",
  166: "If the Gambler is innocent, then so is the Fortuneteller.",
  167: "If the Baroness is guilty, she had at least one accomplice.",
  168: "Blackmail was not the motive.",
  169: "If insanity was the motive, the Diplomat alone must be guilty.",
  170: "The person staying in berth 3 is guilty; the Actress is innocent.",
  171: "The victim, D.V. Uss, could not have been killed after 7 o'clock. Now, if you question the Conductor, you will have enough information to realize that out of questioning the Waiter and searching the Dining, Drawing Room, and Smoking Lounge Areas, only one source of information will prove useful.",
  172: "The only time the Diplomat or Fortuneteller could have committed the crime was between 5 and 6 o'clock; at other times, they were in the dining car.",
  173: "If the murder took place before 6 o'clock, then the Count, Fortuneteller, Gambler, and Heiress must all be innocent; until then, they were all together in a fortunetelling session in the drawing room.",
  174: "Among the suspects, exactly two men and two women are experts on coins.",
  175: "If the Entrepreneur is guilty, the motive was espionage or revenge.",
  176: "If the Count is guilty, the motive was espionage or insanity.",
  177: "Berths 4 and 5 are unoccupied this trip.",
  178: "If the murder took place between 6 and 7 o'clock, then the Count, Diplomat, and Gambler must all be innocent.",
  179: "If the Entrepreneur is guilty, the motive was insanity or jealousy.",
  180: "The motive was not money.",
  181: "The Count could only have committed the crime before 6 o'clock.",
  182: "From 6 until 7, the Actress, Entrepreneur, Fortuneteller, and Gambler were in the dining room.",
  183: "If the Actress is guilty, the motive was jealousy or revenge; the Actress is an expert in jewels but not coins.",
  184: "The four women are staying in berths 1, 2, and 6; the four men are staying in berths 3, 4, and 5.",
  185: "If the Baroness and Heiress are both guilty, then the motive is not insanity or revenge.",
  186: "The only motives I would ever have for murder are jealousy or money.",
  187: "There was just one killer.",
  188: "The murder weapon was not a gun, and there was only one killer.",
  189: "If the Baroness is guilty, the motive was blackmail or insanity.",
  190: "If the victim was John Doe, the motive could not have been jealousy or revenge. If the victim was Jon Doe, the motive could not have been espionage or revenge.",
  191: "From 4 until 5, the Baroness, Count, Diplomat, and Heiress were in the dining room.",
  192: "If the Count is guilty, the motive was not blackmail; the Count cannot pick a lock.",
  193: "One killer was a woman occupying berth 1 or 2.",
  194: "If the Baroness is guilty, the motive was insanity or money.",
  195: "If the Entrepreneur is guilty, the motive was blackmail or revenge.",
  196: "The killer had to know that the victim ate a special diet; but any of the suspects could have known this, since it was discussed aloud earlier in the dining room. The killer had to either poison the victim's food in the kitchen between 4 and 5 o'clock or in the dining room between 5 and 6, while the victim was eating.",
  197: "The victim's name was Claude Fraud. If you question the Cook, the Valet, and the Waiter, you'll realize that at most one of them has useful information.",
  198: "The Fortuneteller could not have committed the crime between 4 and 5 or between 6 and 7, when she was in the dining room.",
  199: "From the angles of the stab wounds, either the killer had to be ambidextrous, or there were at least two killers, one of whom was lefthanded and one of whom was righthanded; the murder occurred sometime between 5 o'clock and 7 in the victim's Second Class berth.",
  200: "The killer walks with a limp.",
  201: "Unless the murder took place after 7 o'clock, the Entrepreneur could not have done it.",
  202: "If the Diplomat is guilty, the motive was espionage, insanity, or jealousy; the Diplomat is an expert in exotic poisons.",
  203: "At least one man and one woman are guilty.",
  204: "Neither the Actress nor the Count could have committed the murder earlier than 5 o'clock.",
  205: "The Diplomat would not have committed murder unless the Fortuneteller helped him. The Fortuneteller can give me a partial alibi.",
  206: "The murder had to take place either before 5 o'clock or after 7.",
  207: "The Entrepreneur and Gambler are sharing berth 4; the Actress and Fortuneteller are sharing berth 6.",
  208: "If the Count is guilty, the motive was blackmail, jealousy, or revenge.",
  209: "The Diplomat could only have committed the crime before 6 o'clock.",
  210: "If the Actress is guilty, the motive was blackmail, insanity, or jealousy; the Actress is righthanded.",
  211: "The Baroness knows three suspects who know very little about either coins or jewels. The Actress and Count know something about which suspects are jewel or coin experts.",
  212: "Both the Diplomat and the Fortuneteller are innocent.",
  213: "If the Actress is guilty, then so is either the Baroness or Heiress, or both.",
  214: "The motive was not espionage or insanity.",
  215: "If the Baroness is guilty, the motive was not jealousy or money.",
  216: "If the Entrepreneur is guilty, the motive was blackmail or espionage.",
  217: "If the Heiress is guilty, the motive was not espionage, jealousy, or revenge; the Heiress knows how to pick a lock.",
  218: "If the Heiress is guilty, the motive was espionage or money; the Heiress is an expert in both coins and jewels.",
  219: "The Heiress speaks French; the Count and the Diplomat do not.",
  220: "The victim had dined with the killer in Paris.",
  221: "If the Gambler is guilty, the motive was money or revenge.",
  222: "If the murder weapon was an icepick, neither the Count nor the Gambler is guilty. The Fortuneteller knows how to determine the murder weapon.",
  223: "The victim was already dead before he was shot.",
  224: "The list of coins the victim was carrying indicates that the killer took only the very best of the coins, and so must have been an expert on coins.",
  225: "A Spanish coin, newly minted, is found on a corner of the kitchen floor.",
  226: "The victim was already dead when he was stabbed.",
  227: "The Count, the Diplomat, and the Gambler, whether acting alone or together, could only have committed the crime before 7 o'clock; after that, they were all in the dining room.",
  228: "From 5 o'clock until 6, only the Diplomat could have committed the crime.",
  229: "If the Count and Gambler are both guilty, then the motive is not blackmail or espionage. The Conductor can give me an alibi from 6 o'clock until 7.",
  230: "If the Entrepreneur is guilty, the motive was blackmail or espionage; the Entrepreneur does not speak French.",
  231: "If the Diplomat is guilty, the motive was espionage, insanity, or money; the Diplomat is not an expert in either coins or jewels.",
  232: "If the motive was blackmail or revenge, then either the Baroness or Count (or both) are guilty.",
  233: "If the Fortuneteller is guilty, the motive was blackmail, money, or revenge; the Fortuneteller is not an expert in exotic poisons.",
  234: "The victim was killed between 4 o'clock and 7 o'clock, but not between 5 and 6. The Diplomat can give the Entrepreneur an alibi.",
  235: "The Valet and Porter are collaborating on a mystery novel called \"The Lefthanded Killer,\" and they always notice what passengers are lefthanded and what ones are righthanded.",
  236: "The Baroness could only have committed the crime after 6 o'clock.",
  237: "If the Diplomat is guilty, the motive was not blackmail, insanity, or money; the Diplomat cannot pick a lock.",
  238: "The Diplomat, Entrepreneur, and Fortuneteller are not experts in either coins or jewels.",
  239: "If the Fortuneteller is guilty, the motive was blackmail or money.",
  240: "The Entrepreneur is not a spy, and could not have killed anyone for the reason of espionage.",
  241: "The only motives I would ever have for murder are blackmail or espionage.",
  242: "If the victim's food was poisoned before 5 o'clock, then the Baroness, Diplomat, Fortuneteller, and Heiress must all be innocent.",
  243: "The victim was still alive at 6 o'clock.",
  244: "If the murder took place after 6 o'clock, then the Baroness, Diplomat, Entrepreneur, and Heiress must all be innocent.",
  245: "If the Actress is guilty, the motive was insanity or money.",
  246: "The Heiress occupies berth 1, and the Entrepreneur occupies berth 4.",
  247: "From 7 until 8, all the male suspects were in the smoking lounge.",
  248: "The motive was not espionage or money.",
  249: "The Heiress could only have committed the crime between 6 and 7 o'clock.",
  250: "The victim was shot in the smoking lounge.",
  251: "At least two men are guilty, as well as a woman who was wearing red shoes.",
  252: "The Fortuneteller is innocent.",
  253: "The motive was not espionage.",
  254: "The Valet and the Doctor will tell you the same thing about the time of death, but the Doctor can also tell you whether or not the victim was poisoned.",
  255: "Between 5 and 7 o'clock, the Actress, Baroness, Diplomat, and Entrepreneur all were in the dining room.",
  256: "If the Diplomat is guilty, the motive was blackmail, money, or revenge; the Diplomat is lefthanded.",
  257: "The murder could not have occurred after 7 o'clock.",
  258: "Of the Fortuneteller and Heiress, at least one is innocent.",
  259: "The motive was either blackmail, espionage, or insanity.",
  260: "Only the Diplomat would have killed because of insanity; and if he is guilty, insanity was his motive.",
  261: "If the Diplomat is guilty, the motive was not espionage or money.",
  262: "The Heiress is innocent.",
  263: "If the Count is guilty, the motive was espionage or jealousy; the Count does not speak French.",
  264: "If the Heiress is guilty, then so is the Actress.",
  265: "If the Gambler is guilty, the motive was money or revenge.",
  266: "The motive was not blackmail or jealousy.",
  267: "If the Heiress is guilty, the motive was espionage or money.",
  268: "None of the male suspects is ambidextrous; one is lefthanded, three are righthanded.",
  269: "The Killer took some coins and jewels (either because it was robbery—i.e., the motive was money—or because he or she wanted it to look that way) but left other coins and jewels behind, in the open. There was only one Killer.",
  270: "If the Count is innocent, then so are the Fortuneteller and Gambler.",
  271: "Among the suspects, at least three of the men are experts in exotic poisons.",
  272: "The killer was a woman who could speak French; she had no accomplices.",
  273: "If the Diplomat is innocent, then the Gambler is guilty; the motive was espionage, jealousy, or money.",
  274: "If the Actress is guilty, the motive was not insanity; the Actress cannot pick a lock.",
  275: "If the victim was a spy, the motive was not espionage.",
  276: "If the Fortuneteller is guilty, the motive was insanity or revenge.",
  277: "From 5 o'clock until 6, the Count, Entrepreneur, and Gambler were in the dining room; the Actress, Baroness, and Diplomat were in the dining room from 6 until 7.",
  278: "The murder could not have occurred between 6 and 7 o'clock.",
  279: "The Doctor, the Cook, and the Conductor were in the dining room from 4 o'clock until 6, and could not have committed the crime during that time.",
  280: "Searching First and Second Class is likely to yield important information.",
  281: "If the Gambler is guilty, the motive was jealousy or money; the Gambler is righthanded.",
  282: "If the food was poisoned between 5 and 6 o'clock, then the Baroness, Count, Entrepreneur, and Heiress must all be innocent.",
  283: "The motive was not espionage or money.",
  284: "The motive could not have been espionage or money.",
  285: "If the murder weapon was a pair of scissors, then either the Baroness, Count, or Gambler is guilty.",
  286: "Among the suspects, exactly three women and one man are experts in jewels.",
  287: "The motive was not blackmail.",
  288: "If the Entrepreneur is innocent, then the motive was not jealousy or money; and if the Entrepreneur is guilty, then the motive was jealousy or money.",
  289: "If the Actress is guilty, the motive was blackmail or insanity; the Actress does not speak French.",
  290: "If the Heiress is guilty, the motive was either blackmail, insanity, or revenge.",
  291: "At least one man is guilty.",
  292: "If the Heiress is guilty, the motive was espionage or insanity; the Gambler is guilty.",
  293: "If the Entrepreneur is guilty, the motive was either blackmail, insanity, or revenge.",
  294: "The occupant of berth 5 is the Count; the Entrepreneur occupies berth 4.",
  295: "The motive was not blackmail, jealousy, or revenge.",
  296: "If the Baroness is guilty, the motive was blackmail, money, or revenge; the Baroness is not an expert in exotic poisons.",
  297: "If the weapon was a sabre, only one of the male suspects would have had the strength to make the fatal blow.",
  298: "The only motives I would ever have for murder are espionage or money.",
  299: "If the victim was killed with a knife, the victim was killed by someone who knocked me out from behind.",
  313: "The Baroness and Entrepreneur are both guilty, but one of them may be lying.",
  314: "The motive was not money or revenge.",
  315: "At least one Killer knows how to pick a lock.",
  316: "The Entrepreneur is innocent.",
  317: "If the weapon was a sabre, the murder must have happened after 5 o'clock; otherwise, it would have been before.",
  318: "If the victim was stabbed to death in First Class between 5 and 7 o'clock with either a kitchen knife or a sword: he was also shot, after he was already dead.",
  319: "The Fortuneteller speaks French; the Actress and Entrepreneur do not.",
  320: "Every berth is occupied by either one of two suspects.",
};

// Ids whose photo was hard to read — flagged for a closer look on /verify.
const UNCERTAIN = new Set<number>([
  18, 118, 121, 122, 123, 126, 132, 133, 134, 137, 142, 143, 147, 148, 149,
  150, 154, 155, 160, 273, 277, 279, 290, 292, 293, 297, 299, 317, 318,
]);

// Full 1..320 clue list. Ids absent from CLUE_TEXT are pending (text: null).
export const CLUES: Clue[] = Array.from({ length: CLUE_COUNT }, (_, i) => {
  const id = i + 1;
  const text = CLUE_TEXT[id] ?? null;
  return { id, text, verified: false, uncertain: text != null && UNCERTAIN.has(id) };
});

export function getClue(id: number | null | undefined): Clue | undefined {
  if (!id) return undefined;
  return CLUES[id - 1];
}
